name = "reverb"
compatibility_date = "2026-01-26"

# Cloudflare Pages will use this as the build output directory.
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "reverb"
database_id = "df01d90a-e8c7-484c-8f87-bde0a6258286"

[vars]
BUN_VERSION = "1.3.8"
NODE_ENV = "production"
PORT = "8080"
SPOTIFY_CLIENT_ID = "b372ddf13dab44809e822ef7693cfe3f"
APP_ORIGIN = "https://reverb-6jy.pages.dev"
SPOTIFY_REDIRECT_URI = "https://reverb-6jy.pages.dev/api/auth/callback"
