name = "reverb"
compatibility_date = "2026-01-26"

# Cloudflare Pages will use this as the build output directory.
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "reverb"
database_id = "df01d90a-e8c7-484c-8f87-bde0a6258286"
